# Copyright (C) strawberryhacker

obj-y += /drivers/apic.o
obj-y += /drivers/clk.o
obj-y += /drivers/ddr.o
obj-y += /drivers/gpio.o
obj-y += /drivers/matrix.o
obj-y += /drivers/uart.o
obj-y += /drivers/wdt.o
obj-y += /drivers/dma.o
