# Copyright (C) strawberryhacker

include $(TOP)/drivers/gpio/Makefile
include $(TOP)/drivers/clk/Makefile
include $(TOP)/drivers/wdt/Makefile
include $(TOP)/drivers/board/Makefile
include $(TOP)/drivers/uart/Makefile
include $(TOP)/drivers/irq/Makefile
include $(TOP)/drivers/matrix/Makefile
