# Copyright (C) strawberryhacker

obj-$(SAMA5D2X) += /drivers/board/sama5d2x_led.o
obj-$(SAMA5D2X) += /drivers/board/sama5d2x_hardware.o
obj-$(SAMA5D2X) += /drivers/board/sama5d2x_serial.o
obj-$(SAMA5D2X) += /drivers/board/sama5d2x_print.o
